### ISSUE TITLE
Program will crash when get-stash-items returns "false"

### ISSUE THREAD

**Issue by celnahal** [bjarkeeck/PathOfExileStashSorter#2]
This is more a bug with the API I think than anything else.

For some background information I played this game 1.5+ years ago and took a break. When I came back I started a character in rampage and have only played there. So I have many characters in the normal league that are untouched, left over from when I used to play.

As a results when you make the call to get-stash-items returns the string "false" for those characters. This causes the program to crash during the initialization process after you login.

I updated the below method as a band aid fix to get things to work on my end for now. I added the jsonData != "false" just to get things working. 

```
    public static List<Tab> FetchTabs(League league)
    {
        string jsonData = WebClinet.DownloadString(string.Format(STASHURL, league.Name, 0));
        if (jsonData != "false")
        {
            Stash stash = JsonConvert.DeserializeObject<Stash>(jsonData);
            List<Tab> tabs = stash.Tabs;
            tabs.ForEach(x => x.League = league);
            return tabs;
        }
        return new List<Tab>();
    }
```

**Comment by bjarkeeck** [comment]
Thank you very much :) It's added.
